import {setupUI,renderQueue,setEmpty,settingsTab,revealComposer} from './ui.js';
import {icon,iconButton,actionIcons,taskState} from './icons.js';
import {TaskQueue} from './task-queue.js';
import {Viewer} from './viewer.js';
import {MAX_REFERENCES} from '../shared/references.js';
import {prepareReferences} from './prepare-references.js';
import {Board} from './canvas.js';
import {Editor} from './editor.js';
import * as disk from './storage.js';
import * as drive from './drive.js';
const $=id=>document.getElementById(id),assets=new Map(),previews=new Map(),replicas=new Map(),uploadStates=new Map();
let saveWaiters=[],sourceAssetId=null;
let revision=0,clientId='',ready=false,busy=false,stop=false,dirty=false,saving=false,conflict=false,saveTimer,references=[],restoreTarget=null,offset=0,driveFiles=[],drivePicked=new Set(),drivePickerBusy=false;
const labels={running:'生成中',succeeded:'生成完成',failed:'失败',unknown:'结果未确认',charged_unknown:'疑似已扣费 · 图片未取回',save_failed:'交付未完成'};
const notice=(t,error=false)=>{$('notice').textContent=t;$('notice').className=error?'error':'';const dialog=document.querySelector('dialog[open]');if(dialog){let n=dialog.querySelector('.dialog-status');if(!n){n=document.createElement('p');n.className='dialog-status';n.setAttribute('role','status');dialog.append(n);}n.textContent=t;n.classList.toggle('error',error);}};
const action=fn=>async(...args)=>{try{await fn(...args);}catch(e){notice(e.message||'操作未完成',true);if(e.detail){$('connection-open').dataset.state='error';$('drive-diagnostic').textContent=drive.diagnostic();$('drive-diagnostic').hidden=false;$('drive-status').textContent=e.message;}}};
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=action(fn);return b;}
async function api(path,opts={}){const r=await fetch(path,{...opts,cache:'no-store',headers:{'X-Workbench-Request':'1',...opts.headers}}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||d.task?.error_message||'请求失败'),{conflict:d.conflict});return d;}
const post=(path,data,method='POST')=>api(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function refreshAssets(){const d=await api('/api/assets');for(const a of d.assets)assets.set(a.id,a);return d.assets;}
const board=new Board($('board'),{change:changed,select:ids=>{$('selection-count').textContent=ids.length+' 张';document.querySelector('.selection-actions').hidden=!ids.length;},open:id=>action(()=>viewItem(id))(),action:kind=>action(()=>run(kind))(),menu:(e,id)=>{const m=$('context-menu');m.replaceChildren(...[['裁切 / 标注','edit'],['用作参考图','reference'],['载入生成参数','params'],['下载原图','download'],['上传到 Drive','drive'],['恢复原图','restore'],['移出画布','remove']].map(([t,a])=>{const b=button(t,()=>{m.hidden=true;return run(a);});b.prepend(icon(actionIcons[a]));b.setAttribute('role','menuitem');return b;}));m.hidden=false;m.style.left=Math.max(8,Math.min(e.clientX,window.innerWidth-208))+'px';m.style.top=Math.max(8,Math.min(e.clientY,window.innerHeight-284))+'px';m.querySelector('button')?.focus();}});
board.info=i=>{const a=assets.get(i.asset_id);if(!a)return{title:i.label,state:i.label};return{width:a.width,height:a.height,uploadState:uploadStates.get(a.id)||(a.metadata.drive?'uploaded':null),url:previews.get(a.id)||a.thumbnail_url,title:a.metadata.prompt||a.metadata.name||(a.metadata.kind==='edit'?'编辑副本':'图片'),state:`${a.width} × ${a.height} · ${replicas.get(a.id)||(a.original_url?'旧云端原图':a.metadata.drive?'Drive 已归档 · 原图待恢复':'本机原图待恢复')}`};};
function changed(){if(!ready)return;dirty=true;$('sync-state').textContent=conflict?'画布冲突，请导出后重载':'正在保存…';clearTimeout(saveTimer);saveTimer=setTimeout(saveWorkspace,650);}
async function saveWorkspace(){if(saving){await new Promise(resolve=>saveWaiters.push(resolve));return saveWorkspace();}if(!ready||!dirty||conflict)return;saving=true;dirty=false;try{const d=await post('/api/workspace',{revision,state:{items:board.items,view:board.view},google_client_id:clientId},'PUT');revision=d.revision;$('sync-state').textContent=dirty?'正在保存…':'画布已同步';}catch(e){dirty=true;conflict=!!e.conflict;$('sync-state').textContent=conflict?'冲突：导出布局后重载':'未同步：请导出布局';notice(e.message,true);}finally{saving=false;for(const resolve of saveWaiters.splice(0))resolve();if(dirty&&!conflict)saveTimer=setTimeout(saveWorkspace,10000);}}
function selectedAssets(){return [...board.selected].map(id=>board.items.find(i=>i.id===id)).map(i=>assets.get(i?.asset_id)).filter(Boolean);}
async function original(a){const blob=await disk.cached(a.id);if(blob)return blob;if(a.original_url){const r=await fetch(a.original_url);if(!r.ok)throw new Error('旧原图无法读取');const b=await r.blob();await disk.keep(a.id,b).catch(()=>{});replicas.set(a.id,'旧原图 · 本机可用');return b;}throw new Error('此电脑缺少原图。请选择“恢复原图”，从本地文件或已归档 Drive 恢复。');}
async function preview(a,blob){const thumb=await disk.thumbnail(blob),old=previews.get(a.id);if(old)URL.revokeObjectURL(old);previews.set(a.id,URL.createObjectURL(thumb));board.render();try{const d=await post('/api/assets/'+a.id+'/thumbnail',{data:(await disk.dataURL(thumb)).split(',')[1]},'PUT');assets.set(a.id,d.asset);}catch(e){notice('原图已接收；缩略图暂未同步：'+e.message,true);}}
async function retain(a,blob,{autoSave=false}={}){let recovered=false,saved=false;try{await disk.keep(a.id,blob);recovered=true;replicas.set(a.id,'本机恢复缓存');}catch(e){replicas.set(a.id,'仅本页内存 · 立即下载');notice(e.message,true);}if(autoSave)try{saved=await disk.saveFile(a,blob);if(saved)replicas.set(a.id,'本地文件已校验');}catch(e){notice(e.message,true);}board.render();if(!recovered&&!saved){stop=true;queue.cancel();disk.download(blob,disk.filename(a));notice('缓存和文件夹保存均未成功；已发起下载并暂停后续生成。请确认原图已保存再关闭页面。',true);}return{recovered,saved};}
async function createAsset(blob,extra={}){if(!['image/png','image/jpeg','image/webp'].includes(blob.type)||blob.size>20*1024*1024)throw new Error('请选择不超过 20 MiB 的 PNG/JPEG/WebP 原图');const bitmap=await createImageBitmap(blob),dims={width:bitmap.width,height:bitmap.height};bitmap.close();if(dims.width*dims.height>80000000)throw new Error('图片像素数量过大');const id=crypto.randomUUID();await disk.keep(id,blob).catch(()=>{});let a;try{a=(await post('/api/assets',{id,mime:blob.type,...dims,sha256:await disk.hash(blob),...extra})).asset;}catch(e){disk.download(blob,'ctmoai-unsynced-'+id+'.png');throw new Error('档案未创建，已发起文件下载。'+e.message);}assets.set(a.id,a);await retain(a,blob,{autoSave:!!extra.parent_asset_id});await preview(a,blob);return a;}
async function importFiles(files){let n=0;for(const f of files){const a=await createAsset(f,{name:f.name});board.add({asset_id:a.id,x:60+n%4*300,y:60+Math.floor(n/4)*330});n++;}notice(`已导入 ${n} 张图片`);}
const editor=new Editor($('editor'),async(blob,parent,recipe)=>{const a=await createAsset(blob,{parent_asset_id:parent.id,recipe,name:'编辑副本'});const src=board.items.find(i=>i.asset_id===parent.id);board.add({asset_id:a.id,x:(src?.x||0)+300,y:src?.y||0});notice('已创建编辑副本，原图保留。可下载或上传 Drive。');});
const viewer=new Viewer($('viewer'),original);
async function viewItem(id){const i=board.items.find(i=>i.id===id),a=assets.get(i?.asset_id);if(!a)throw new Error('这张图片尚未生成完成');await viewer.open(a);}
function formArgs(){return{prompt:$('prompt').value,image_size:$('size').value,aspect_ratio:$('ratio').value};}
function checkReferences(refs){if(refs.length>MAX_REFERENCES)throw new Error('参考图最多 14 张');}
function referenceBudget(){$('ref-budget').textContent=`${references.length} / 14`; }
function updateParameterSummary(){$('parameter-summary').textContent=`${$('size').value} · ${$('ratio').value} · ${$('batch-count').value||1} 张`;}
async function taskDelivered(t){const a=assets.get(t.id);if(!a)return!!t.image_url;if(a.thumbnail_url||previews.has(a.id))return true;try{return!!await disk.cached(a.id);}catch{return false;}}
const taskLabel=(t,delivered=false)=>t.status==='succeeded'?(delivered?'生成完成':t.recovery_url?'生成成功 · 可重新拉取':'生成成功 · 交付未完成'):(labels[t.status]||t.status||'未完成');
async function reconcileTask(t){const item=board.items.find(i=>i.id===t.id&&!i.asset_id);if(!item)return false;const delivered=await taskDelivered(t),a=assets.get(t.id);if(t.status==='succeeded'&&delivered&&a)item.asset_id=a.id;item.label=taskLabel(t,delivered);return true;}
async function discardRecovery(t){if(!t?.recovery_url)return;try{await api(t.recovery_url,{method:'DELETE'});t.recovery_url=null;t.recovery_expires_at=null;}catch{}}
async function recoverTask(t,{silent=false}={}){if(!t.recovery_url)throw new Error(t.request_id?'供应商采用同步接口，无法仅凭请求编号重新下载；此任务也没有本站恢复副本。':'此任务没有可重新拉取的恢复副本');const r=await fetch(t.recovery_url,{cache:'no-store'});if(!r.ok){let message='恢复副本已过期或不可用';try{message=(await r.json()).error||message;}catch{}throw new Error(message);}const blob=await r.blob();let a=assets.get(t.id);if(!a)a=await createAsset(blob,{name:'重新拉取的生成图片'});else{await retain(a,blob,{autoSave:true});await preview(a,blob);}const item=board.items.find(i=>i.id===t.id);if(item){item.asset_id=a.id;item.label='生成完成';}else board.add({asset_id:a.id});board.render();changed();if(await disk.cached(a.id))await discardRecovery(t);if(!silent){$('history-dialog').close();notice('图片已重新拉取并恢复到画布，不会再次调用供应商或重复扣费。');}return a;}
async function reconcileBilling(t){const key=$('key').value.trim();if(!key){settingsTab('connections');$('settings-open').click();$('key').focus();throw new Error('请先输入本次页面的 API Key，再核对供应商消费记录');}const d=await post('/api/tasks/'+t.id+'/reconcile',{key});notice(d.message||'供应商消费记录核对完成',!!d.match);await history();return d;}
const readableBytes=n=>n>=1048576?(n/1048576).toFixed(1)+' MiB':Math.max(1,Math.round(n/1024))+' KiB';
const existingDriveAsset=id=>[...assets.values()].find(a=>a.metadata.drive?.file_id===id);
function updateDrivePicker(){const remaining=MAX_REFERENCES-references.length,count=drivePicked.size;$('drive-picker-count').textContent=count?`已选择 ${count} 张 · 还可添加 ${remaining-count} 张`:`尚未选择 · 还可添加 ${remaining} 张`;$('drive-picker-import').disabled=drivePickerBusy||!count;}
function renderDrivePicker(){const list=$('drive-picker-list');list.replaceChildren();const remaining=MAX_REFERENCES-references.length;if(!driveFiles.length){const empty=document.createElement('p');empty.className='section-empty';empty.textContent='没有找到本工作台可访问的 Drive 图片。';list.append(empty);updateDrivePicker();return;}for(const file of driveFiles){const size=Number(file.size),tooLarge=!Number.isSafeInteger(size)||size<1||size>20*1024*1024,existing=existingDriveAsset(file.id),label=document.createElement('label');label.className='drive-file-option';const check=document.createElement('input');check.type='checkbox';check.checked=drivePicked.has(file.id);check.disabled=tooLarge||drivePickerBusy;check.onchange=()=>{if(check.checked&&drivePicked.size>=remaining){check.checked=false;$('drive-picker-status').textContent='本次最多还能添加 '+remaining+' 张参考图。';return;}if(check.checked)drivePicked.add(file.id);else drivePicked.delete(file.id);updateDrivePicker();};const copy=document.createElement('span');copy.className='drive-file-copy';const name=document.createElement('strong');name.textContent=file.name||'未命名图片';const meta=document.createElement('small');meta.textContent=[file.mimeType.replace('image/','').toUpperCase(),Number.isSafeInteger(size)&&size>0?readableBytes(size):'大小未知',file.modifiedTime?new Date(file.modifiedTime).toLocaleString():''].filter(Boolean).join(' · ');copy.append(name,meta);const state=document.createElement('span');state.className='drive-file-state';state.textContent=tooLarge?'超过 20 MiB':existing?'已在工作台':'可导入';label.append(check,copy,state);list.append(label);}updateDrivePicker();}
async function loadDrivePicker(){if(drivePickerBusy)return;drivePickerBusy=true;$('drive-picker-status').textContent='正在读取 Drive 图片…';$('drive-picker-refresh').disabled=true;updateDrivePicker();try{driveFiles=await drive.listImages();const ids=new Set(driveFiles.map(f=>f.id));drivePicked=new Set([...drivePicked].filter(id=>ids.has(id)));renderDrivePicker();$('drive-picker-status').textContent=driveFiles.length?`找到 ${driveFiles.length} 张可访问图片，按最近修改排序。`:'当前授权范围内还没有可导入图片。';}finally{drivePickerBusy=false;$('drive-picker-refresh').disabled=false;renderDrivePicker();}}
async function driveFileAsAsset(file){let a=existingDriveAsset(file.id);if(a){try{await original(a);}catch{const blob=await drive.restore(a);await retain(a,blob);await preview(a,blob);}if(!board.items.some(i=>i.asset_id===a.id))board.add({asset_id:a.id});return a;}const blob=await drive.downloadImage(file);a=await createAsset(blob,{name:file.name||'Drive 图片'});const saved=await post('/api/assets/'+a.id+'/drive',{file_id:file.id,sha256:a.sha256,size:blob.size},'PUT');a=saved.asset;assets.set(a.id,a);replicas.set(a.id,'Drive 导入 · 本机可用');board.add({asset_id:a.id});return a;}
async function importDriveReferences(){if(drivePickerBusy)return;const picked=driveFiles.filter(f=>drivePicked.has(f.id));if(!picked.length)return;const additions=picked.filter(file=>{const a=existingDriveAsset(file.id);return!a||!references.some(r=>r.asset.id===a.id);});if(additions.length+references.length>MAX_REFERENCES)throw new Error('参考图最多 14 张');drivePickerBusy=true;$('drive-picker-refresh').disabled=true;$('drive-picker-import').disabled=true;const imported=[];try{for(let i=0;i<picked.length;i++){$('drive-picker-status').textContent=`正在导入 ${i+1} / ${picked.length}：${picked[i].name||'未命名图片'}`;imported.push(await driveFileAsAsset(picked[i]));}await useReferences(imported);$('drive-picker').close();notice(`已从 Drive 导入 ${additions.length} 张参考图。`);}catch(e){if(imported.length)await useReferences(imported).catch(()=>{});throw e;}finally{drivePickerBusy=false;$('drive-picker-refresh').disabled=false;renderDrivePicker();}}
function renderReferences(){$('ref-preview').replaceChildren();$('ref-preview').hidden=!references.length;$('ref-drop-hint').hidden=!!references.length;references.forEach((r,n)=>{const row=document.createElement('div');row.className='reference-row';row.tabIndex=0;row.setAttribute('role','group');row.setAttribute('aria-label',`图 ${n+1}，双击或按 Enter 查看大图`);row.title=`图 ${n+1} · ${r.asset.metadata.name||'画布原图'} · ${(r.blob.size/1000000).toFixed(1)} MB · 双击查看大图`;row.ondblclick=e=>{if(!e.target.closest('button'))action(()=>viewer.open(r.asset))();};row.onkeydown=e=>{if(e.key==='Enter'&&e.target===row){e.preventDefault();action(()=>viewer.open(r.asset))();}};const img=document.createElement('img');img.src=r.url;img.alt='参考图 '+(n+1);const index=document.createElement('span');index.className='ref-index';index.textContent=n+1;const controls=document.createElement('div');controls.className='ref-controls';const up=iconButton('up','图 '+(n+1)+' 提前',()=>{if(busy||n===0)return;[references[n-1],references[n]]=[references[n],references[n-1]];renderReferences();}),down=iconButton('down','图 '+(n+1)+' 后移',()=>{if(busy||n===references.length-1)return;[references[n+1],references[n]]=[references[n],references[n+1]];renderReferences();}),remove=iconButton('x','移除图 '+(n+1),()=>{if(busy)return;URL.revokeObjectURL(r.url);references.splice(n,1);renderReferences();});up.disabled=n===0;down.disabled=n===references.length-1;controls.append(up,down,remove);row.append(img,index,controls);$('ref-preview').append(row);});$('clear-ref').hidden=!references.length;referenceBudget();}
function clearReference(){references.forEach(r=>URL.revokeObjectURL(r.url));references=[];$('reference').value='';renderReferences();}
async function useReferences(list){if(busy)throw new Error('请等待本次参考图准备完成');const unique=list.filter((a,i)=>!references.some(r=>r.asset.id===a.id)&&list.findIndex(x=>x.id===a.id)===i);if(unique.length+references.length>MAX_REFERENCES)throw new Error('参考图最多 14 张');const additions=[];for(const a of unique)additions.push({asset:a,blob:await original(a)});checkReferences([...references,...additions]);for(const r of additions){r.url=URL.createObjectURL(r.blob);references.push(r);}renderReferences();if(list.length)revealComposer();notice('参考图已添加，可用“图 1、图 2”说明用途。');}
async function useReference(a){return useReferences([a]);}
async function parameters(a){if(busy)throw new Error('请等待本次参考图准备完成');revealComposer();const p=a.metadata;sourceAssetId=a.id||null;if(!p.prompt)throw new Error('此图片没有生成参数');$('prompt').value=p.prompt;$('model').value=p.model;$('size').value=p.image_size;$('ratio').value=p.aspect_ratio;updateParameterSummary();clearReference();const ids=p.reference_asset_ids|| (p.reference_asset_id?[p.reference_asset_id]:[]);const refs=ids.map(id=>assets.get(id));if(refs.some(r=>!r))throw new Error('参数已载入，但部分原参考图档案已移除，请重新选择');await useReferences(refs);notice('已载入参数，尚未提交生成请求。');}
async function run(kind){if(kind==='remove'){board.remove();return;}const chosen=selectedAssets();if(!chosen.length)throw new Error('请先选择已完成的图片');const a=chosen[0];if(['view','edit','params','restore'].includes(kind)&&chosen.length!==1)throw new Error('此操作请只选择一张图片');
 if(kind==='view')return viewer.open(a);if(kind==='edit')return editor.open(await original(a),a);if(kind==='reference')return useReferences(chosen);if(kind==='params')return parameters(a);
 if(kind==='download'){for(const a of chosen){const blob=await original(a);let wrote=false;try{wrote=await disk.saveFile(a,blob);}catch{}if(wrote){replicas.set(a.id,'本地文件已校验');}else{disk.download(blob,disk.filename(a));replicas.set(a.id,'下载已发起 · 缓存保留');}}board.render();notice('保存操作完成。普通下载请在浏览器下载列表中确认。');}
 if(kind==='drive'){if(!drive.connected()){settingsTab('connections');$('settings-open').click();throw new Error('请先连接 Google Drive，再点击上传选中的图片');}for(const a of chosen){uploadStates.set(a.id,'uploading');board.render();try{notice('正在上传并校验原图…');const blob=await original(a),v=await drive.upload(a,blob);const d=await post('/api/assets/'+a.id+'/drive',{file_id:v.id,sha256:v.sha256,size:v.size},'PUT');assets.set(a.id,d.asset);replicas.set(a.id,(replicas.get(a.id)||'本机可用')+' · Drive 已校验');uploadStates.set(a.id,'uploaded');}catch(e){uploadStates.set(a.id,'error');throw e;}finally{board.render();}}board.render();notice('原图已上传到 Drive，文件校验通过。');}
 if(kind==='restore'){if(a.metadata.drive&&drive.connected()){notice('正在从 Drive 恢复原图…');const blob=await drive.restore(a);await retain(a,blob);await preview(a,blob);notice('Drive 原图已恢复并通过校验。');}else{restoreTarget=a;$('restore-file').value='';$('restore-file').click();notice(a.metadata.drive?'选择匹配的本地原图，或先连接 Drive 后再次点击恢复。':'请选择对应的本地原图，系统会校验文件内容。');}}
}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=action(()=>run(b.dataset.action)));
$('restore-file').onchange=action(async()=>{const f=$('restore-file').files[0],a=restoreTarget;if(!f||!a)return;if(!a.sha256||await disk.hash(f)!==a.sha256)throw new Error('文件内容与原图不一致，请选择最初保存的原文件');await retain(a,new Blob([f],{type:a.mime}));await preview(a,f);notice('原图已匹配并恢复。');});
async function addReferenceFiles(files){files=[...files];if(!files.length)return;checkReferences([...references,...files.map(blob=>({blob}))]);const list=[];for(const f of files){const a=await createAsset(f,{name:f.name});board.add({asset_id:a.id});list.push(a);}await useReferences(list);$('reference').value='';}
$('reference').onchange=action(()=>addReferenceFiles($('reference').files));
for(const type of ['dragenter','dragover'])$('reference-dropzone').addEventListener(type,e=>{e.preventDefault();e.stopPropagation();$('reference-dropzone').classList.add('is-dragging');});
$('reference-dropzone').addEventListener('dragleave',e=>{if(!$('reference-dropzone').contains(e.relatedTarget))$('reference-dropzone').classList.remove('is-dragging');});
$('reference-dropzone').addEventListener('drop',action(async e=>{e.preventDefault();e.stopPropagation();$('reference-dropzone').classList.remove('is-dragging');await addReferenceFiles(e.dataTransfer.files);}));
$('drive-reference').onclick=action(async()=>{if(!drive.connected()){settingsTab('connections');$('settings-open').click();throw new Error('请先连接 Google Drive，再从 Drive 选择参考图');}if(references.length>=MAX_REFERENCES)throw new Error('参考图已达到 14 张上限');drivePicked.clear();$('drive-picker').showModal();await loadDrivePicker();});
$('drive-picker-refresh').onclick=action(loadDrivePicker);$('drive-picker-import').onclick=action(importDriveReferences);
for(const id of ['model','size','ratio','batch-count'])$(id).addEventListener('input',updateParameterSummary);
$('prompt').addEventListener('input',referenceBudget);
$('import').onchange=action(async()=>{await importFiles($('import').files);$('import').value='';});
$('board').addEventListener('dragover',e=>e.preventDefault());$('board').addEventListener('drop',action(async e=>{e.preventDefault();await importFiles(e.dataTransfer.files);}));
$('clear-ref').onclick=clearReference;$('clear-key').onclick=()=>{clearSessionKey();notice('本页 Key 已清除，等待任务已取消；已提交的请求继续接收结果。');};
$('choose-dir').onclick=action(async()=>{$('local-state').textContent='自动保存到本机文件夹：'+await disk.chooseDirectory();});
const queue=new TaskQueue({limit:3,run:runJob,onChange:queueStatus,onCancel:item=>{item.card.label='已取消 · 未提交';syncCard(item);finishBatch(item.batch);},onError:(e,item)=>notice(e.message,true)});
function clearSessionKey(){$('key').value='';stop=true;queue.cancel();for(const item of queue.running.values())item.batch.key=null;}
function queueStatus(){$('queue-status').textContent=queue.size?`生成中 ${queue.running.size} · 等待 ${queue.pending.length}`:'最多 3 个并行任务';if(queue.size)$('queue-panel').open=true;else if(!busy)$('queue-panel').open=false;$('stop').hidden=!busy&&!queue.pending.length;$('stop').disabled=false;$('generate').replaceChildren(icon(busy?'loading':'play',busy?'spin':''),document.createTextNode(busy?'准备参考图…':'生成图片'));const active=[...queue.running.values(),...queue.pending].map(item=>({id:item.id,prompt:item.batch.params?.prompt,state:queue.running.has(item.id)?'generating':'queued',label:queue.running.has(item.id)?item.card.label:'等待生成'}));const recent=board.items.filter(i=>!active.some(a=>a.id===i.id)&&i.label).slice(-3).reverse().map(i=>({id:i.id,prompt:assets.get(i.asset_id)?.metadata.prompt||'图片任务',state:taskState(i.label,!!i.asset_id),label:i.label}));renderQueue([...active,...recent],id=>{const item=board.items.find(i=>i.id===id);if(!item)return;const r=$('board').getBoundingClientRect(),size=board.dimensions(item);board.view.x=r.width/2-(item.x+size.width/2)*board.view.z;board.view.y=r.height/2-(item.y+size.height/2)*board.view.z;board.selected=new Set([id]);board.render();changed();});}
function finishBatch(batch){batch.remaining--;if(batch.remaining===0){batch.key=null;batch.params=null;}}
function syncCard(item){const current=board.items.find(i=>i.id===item.id);if(current){current.label=item.card.label;if(item.card.asset_id)current.asset_id=item.card.asset_id;}board.render();changed();queueStatus();}
$('stop').onclick=()=>{stop=true;const n=queue.cancel();notice(`已取消 ${n} 个等待任务。已提交的任务继续接收结果。`);};
$('form').onsubmit=action(async e=>{e.preventDefault();$('generation-options').open=false;if(busy)return;if(!ready||conflict)throw new Error('请先解决画布同步问题再生成');const count=Number($('batch-count').value);if(!Number.isInteger(count)||count<1||count>8)throw new Error('生成次数为 1–8');if(queue.size+count>12)throw new Error('当前页面最多容纳 12 个运行或等待任务，请稍后再添加');if(assets.size+queue.size+count>2000)throw new Error('图片档案最多 2000 张，请先整理');const sessionKey=$('key').value.trim();if(!sessionKey){settingsTab('connections');$('settings-open').click();$('key').focus();throw new Error('请填写本次页面的 API Key 后生成');}const prompt=$('prompt').value;if(prompt.includes(sessionKey))throw new Error('提示词中包含 API Key，请移除');checkReferences(references);
 busy=true;stop=false;$('controls').disabled=true;queueStatus();let batch=null,cards=[];
 try{const args={prompt,model:$('model').value,image_size:$('size').value,aspect_ratio:$('ratio').value};notice('正在检查 API Key 与供应商连接…');const check=await post('/api/preflight',{key:sessionKey,model:args.model});notice(check.warning||'自检通过，正在准备本组参考图…',!!check.warning);const prepared=await prepareReferences(args,references,{progress:(i,n)=>notice(`正在优化本组参考图 ${i} / ${n}…`),isCancelled:()=>stop});if(stop)throw new Error('已取消准备，尚未提交');
 const params={...args,delivery:'local',...(sourceAssetId?{source_asset_id:sourceAssetId}:{}),reference_images:prepared.images,reference_asset_ids:references.map(r=>r.asset.id),reference_preparation:prepared.records};
 batch={id:crypto.randomUUID(),params,key:sessionKey,remaining:count};
 const rect=$('board').getBoundingClientRect(),point=board.point(rect.left+60,rect.top+60);let y=point.y;while(board.items.some(i=>Math.abs(i.x-point.x)<780&&i.y+242>y&&i.y<y+Math.ceil(count/3)*270))y+=270;
 cards=Array.from({length:count},(_,n)=>board.add({id:crypto.randomUUID(),x:point.x+n%3*300,y:y+Math.floor(n/3)*330,label:'等待生成'}));
 await saveWorkspace();if(stop||dirty||conflict||saving)throw new Error(stop?'已取消，尚未提交':'画布未同步，尚未提交供应商');
 queue.add(cards.map(card=>({id:card.id,card,batch})));notice(`已加入 ${count} 个任务`);batch=null;
 }catch(e){if(batch){batch.key=null;batch.params=null;}for(const c of cards)c.label='未提交';board.render();changed();throw e;}
 finally{busy=false;$('controls').disabled=false;queueStatus();}});
async function runJob(item){const {batch,card}=item,params=batch.params;card.label='生成中';syncCard(item);let complete=null;
 try{const res=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Request':'1'},body:JSON.stringify({...params,id:card.id,key:batch.key}),cache:'no-store'});
 if(!res.headers.get('content-type')?.includes('application/x-ndjson')){const d=await res.json();if(d.task)complete={task:d.task};else throw new Error(d.error||'提交失败');}
 else{const reader=res.body.getReader(),dec=new TextDecoder();let buffer='';for(;;){const{done,value}=await reader.read();if(done)break;buffer+=dec.decode(value,{stream:true});let split;while((split=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,split);buffer=buffer.slice(split+1);if(!line)continue;const msg=JSON.parse(line);if(msg.type==='waiting'){card.label=`生成中 · ${Math.round(msg.elapsed_ms/1000)} 秒`;syncCard(item);};if(msg.type==='complete')complete=msg;}}}
 if(!complete)throw new Error('连接中断，结果未确认。请先检查供应商记录，勿直接重试');
 const pic=complete.output||complete.fallback;if(pic){const blob=disk.decode(pic);let a=complete.asset,kept;if(!a){a=await createAsset(blob,{name:'交付恢复图片'});kept={recovered:!!await disk.cached(a.id)};}else{assets.set(a.id,a);kept=await retain(a,blob,{autoSave:true});await preview(a,blob);}card.asset_id=a.id;card.label='生成完成';if(kept.recovered||kept.saved)await discardRecovery(complete.task);notice(replicas.get(a.id)?.startsWith('仅本页')?'原图仅在本页内存，已发起下载，请确认保存后再关闭。':stop?'原图已接收。后续次数已停止。':'图片已生成，可下载或上传 Drive。',replicas.get(a.id)?.startsWith('仅本页')); }
 else if(complete.task.status==='succeeded'){await refreshAssets();if(complete.task.recovery_url)await recoverTask(complete.task,{silent:true});const delivered=await taskDelivered(complete.task),a=assets.get(card.id);if(delivered&&a)card.asset_id=a.id;card.label=taskLabel(complete.task,delivered);notice(delivered?'已从恢复副本取回图片，不会重复扣费。':'供应商已生成成功，但图片没有交付到当前页面。请在记录中使用“重新拉取图片”。',!delivered);if(!delivered)queue.cancel(batch.id);}
 else{card.label=taskLabel(complete.task);notice(complete.task.error_message||'图片未返回，请检查任务记录',true);queue.cancel(batch.id);}

 }catch(e){let reconciled=false;try{const d=await api('/api/tasks/'+card.id);await refreshAssets();if(d.task.status==='succeeded'&&d.task.recovery_url)await recoverTask(d.task,{silent:true});const delivered=await taskDelivered(d.task),a=assets.get(card.id);if(d.task.status==='succeeded'&&delivered&&a)card.asset_id=a.id;card.label=taskLabel(d.task,delivered);reconciled=true;if(d.task.status==='succeeded'&&delivered)notice('连接中断后已从恢复副本取回图片，不会重复扣费。');else if(d.task.status==='succeeded'&&!delivered)notice(d.task.recovery_url?'供应商已生成成功，可在记录中点击“重新拉取图片”。':'供应商已生成成功，但该任务没有可拉取的恢复副本。',true);else if(d.task.status==='running')notice('页面连接已中断，供应商结果尚未返回本站；请保持页面打开或稍后查看记录。',true);else notice(d.task.error_message||e.message,true);}catch{}if(!reconciled){card.label='未完成 · 查看任务记录';notice(e.message,true);}queue.cancel(batch.id);}
 finally{syncCard(item);finishBatch(batch);history().catch(e=>notice(e.message,true));}
}
async function history(more=false){if(!more)await refreshAssets();const d=await api('/api/tasks?offset='+(more?offset:0));if(!more){$('history').replaceChildren();offset=0;}offset+=d.tasks.length;$('more').hidden=!d.more;$('storage').textContent=`云端图片 ${(d.usage.bytes/1048576).toFixed(1)} / 256 MiB · 新图仅缩略图`;let boardChanged=false;for(const t of d.tasks){const delivered=await taskDelivered(t);if(await reconcileTask(t))boardChanged=true;const div=document.createElement('div');div.className='history-row';const heading=document.createElement('div');heading.className='history-header';const badge=document.createElement('span');badge.className='badge';badge.dataset.state=t.status==='succeeded'&&delivered?'connected':t.status==='running'?'generating':'error';badge.textContent=taskLabel(t,delivered);const time=document.createElement('time');time.textContent=new Date(t.created_at).toLocaleString();heading.append(badge,time);const prompt=document.createElement('details');const summary=document.createElement('summary');summary.textContent=(t.prompt||'无提示词').slice(0,90);const p=document.createElement('p');p.textContent=t.prompt;prompt.append(summary,p);div.append(heading,prompt,button('载入参数',async()=>{await parameters(assets.get(t.id)||{metadata:t});if(t.reference_url){const f=await(await fetch(t.reference_url)).blob(),a=await createAsset(f,{name:'旧任务参考图'});await useReference(a);}$('history-dialog').close();}),button('导出参数',()=>disk.download(new Blob([JSON.stringify(t,null,2)],{type:'application/json'}),t.id+'.json')));
 if(t.recovery_url)div.append(button('重新拉取图片',()=>recoverTask(t)));
 if(['unknown','charged_unknown'].includes(t.status))div.append(button('重新核对供应商记录',()=>reconcileBilling(t)));
 if(t.image_url)div.append(button('加入画布 / 保留旧原图',async()=>{let a=[...assets.values()].find(a=>a.legacy_task_id===t.id);if(!a){a=(await post('/api/assets',{id:crypto.randomUUID(),legacy_task_id:t.id})).asset;assets.set(a.id,a);const blob=await original(a);await preview(a,blob);}board.add({asset_id:a.id});$('history-dialog').close();notice('旧原图已加入档案，保留云端原文件。');}));
 if(t.status==='succeeded'&&!delivered&&!t.recovery_url){const unavailable=document.createElement('p');unavailable.className='hint';unavailable.textContent='此任务没有可下载的恢复副本；同步生图接口不能仅凭请求编号再次取得响应图片。';div.append(unavailable);}
 if(t.request_id){const request=document.createElement('p');request.className='metadata';request.textContent='供应商请求编号：'+t.request_id;div.append(request);}const local=document.createElement('p');local.className='metadata';local.textContent='本站任务编号：'+t.id;div.append(local);
 if(t.status!=='running')div.append(button('删除任务',async()=>{if(!confirm('删除任务记录及旧版云端文件？已下载的文件和独立图片档案不受影响。'))return;await api('/api/tasks/'+t.id,{method:'DELETE'});await history();}));if(t.error_message){const err=document.createElement('p');err.textContent=t.error_message;div.append(err);}$('history').append(div);}if(boardChanged){board.render();changed();queueStatus();}if(!$('history').children.length){const empty=document.createElement('p');empty.className='section-empty';empty.textContent='暂无生成记录';$('history').append(empty);}}
function archive(){$('archive').replaceChildren();if(!assets.size){const p=document.createElement('p');p.className='section-empty';p.textContent='暂无图片档案';$('archive').append(p);}for(const a of assets.values()){const div=document.createElement('div');div.className='archive-card';const url=previews.get(a.id)||a.thumbnail_url;if(url){const img=document.createElement('img');img.src=url;img.loading='lazy';img.alt='图片缩略图';div.append(img);}const p=document.createElement('p');p.textContent=(a.metadata.prompt||a.metadata.name||'图片').slice(0,60);const actions=document.createElement('div');actions.className='archive-actions';div.append(p,actions);actions.append(button('加入画布',()=>{board.add({asset_id:a.id});$('history-dialog').close();}),button('导出档案',()=>disk.download(new Blob([JSON.stringify(a,null,2)],{type:'application/json'}),a.id+'.json')),button('删除档案',async()=>{if(board.items.some(i=>i.asset_id===a.id))throw new Error('请先将图片移出画布');if(!confirm('删除云端缩略图及档案？不会删除本地或 Drive 原图。旧原图将恢复普通任务到期清理。'))return;await api('/api/assets/'+a.id,{method:'DELETE'});assets.delete(a.id);archive();}));$('archive').append(div);}}
$('history-open').onclick=action(async()=>{archive();$('history-dialog').showModal();$('history').innerHTML='<p class="section-empty" role="status">正在载入记录…</p>';await history();});$('more').onclick=action(()=>history(true));
$('select-mode').onclick=()=>{board.mode='select';$('select-mode').classList.add('active');$('pan-mode').classList.remove('active');$('select-mode').setAttribute('aria-pressed','true');$('pan-mode').setAttribute('aria-pressed','false');};$('pan-mode').onclick=()=>{board.mode='pan';$('pan-mode').classList.add('active');$('select-mode').classList.remove('active');$('pan-mode').setAttribute('aria-pressed','true');$('select-mode').setAttribute('aria-pressed','false');};$('fit').onclick=()=>board.fit();$('zoom-in').onclick=()=>board.zoom(1.25);$('zoom-out').onclick=()=>board.zoom(.8);
$('export-layout').onclick=()=>disk.download(new Blob([JSON.stringify({format:'ctmoai-canvas-v1',revision,items:board.items,view:board.view,assets:[...assets.values()]},null,2)],{type:'application/json'}),'ctmoai-canvas.json');
$('reload').onclick=()=>{if(busy||queue.size){notice('生成中，请等待完成。',true);return;}if((dirty||conflict)&&!confirm('本页布局尚未同步。请先导出备份。现在重新载入云端画布？'))return;location.reload();};
$('settings-open').onclick=()=>{$('google-client').value=clientId;$('drive-config').open=!clientId;$('settings').showModal();drive.prepare(clientId).catch(e=>{$('drive-status').textContent=e.message;});};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('save-settings').onclick=action(async()=>{const id=$('google-client').value.trim();if(id&&!/^[a-zA-Z0-9-]+\.apps\.googleusercontent\.com$/.test(id))throw new Error('Client ID 格式无效');if(id!==clientId){drive.disconnect();$('drive-diagnostic').hidden=true;}clientId=id;changed();await saveWorkspace();await drive.prepare(clientId);$('drive-status').textContent='配置已提交，请点击连接 Google Drive';});
$('drive-connect').onclick=action(async()=>{await drive.connect(clientId);$('drive-status').textContent='已授权，正在检查 Drive API…';await drive.checkAccess();$('drive-diagnostic').hidden=true;$('drive-status').textContent='Connected';});$('drive-check').onclick=action(async()=>{$('drive-status').textContent='正在检查…';await drive.checkAccess();$('drive-diagnostic').hidden=true;$('drive-status').textContent='Connected';});$('drive-disconnect').onclick=()=>{drive.disconnect();$('drive-diagnostic').hidden=true;$('drive-status').textContent='已断开本页连接';};$('site-origin').textContent=location.origin;
window.addEventListener('pointerdown',e=>{if(!e.target.closest('#context-menu'))$('context-menu').hidden=true;if($('generation-options').open&&!$('generation-options').contains(e.target))$('generation-options').open=false;});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('generation-options').open)$('generation-options').open=false;});window.addEventListener('beforeunload',e=>{if(busy||queue.size||dirty||[...replicas.values()].some(v=>v.startsWith('仅本页'))){e.preventDefault();e.returnValue='';}});window.addEventListener('pagehide',clearSessionKey);window.addEventListener('pageshow',e=>{if(e.persisted)$('key').value='';});
async function start(){const [w,a]=await Promise.all([api('/api/workspace'),api('/api/assets')]);revision=w.revision;clientId=w.google_client_id;a.assets.forEach(a=>assets.set(a.id,a));board.items=w.state.items||[];board.view=w.state.view||{x:40,y:40,z:1};let reconciled=false;for(const i of board.items){if(!i.asset_id&&assets.has(i.id)){i.asset_id=i.id;reconciled=true;}else if(!i.asset_id&&/生成中|等待提交|等待生成/.test(i.label)){i.label='页面曾中断 · 查看任务记录';reconciled=true;}}ready=true;setEmpty('ready');board.render();queueStatus();if(reconciled)changed();$('sync-state').textContent='画布已同步';for(const a of assets.values()){const blob=await disk.cached(a.id);if(blob){replicas.set(a.id,'本机恢复缓存');if(!a.thumbnail_url)await preview(a,blob);}}board.render();const dir=await disk.restoreDirectory();if(dir)$('local-state').textContent='自动保存到本机文件夹：'+dir;await history();}
setupUI({onAction:kind=>action(()=>run(kind))(),isDriveConnected:drive.connected});
$('key').value='';renderReferences();updateParameterSummary();queueStatus();setEmpty('loading');action(async()=>{try{await start();}catch(e){setEmpty('error');throw e;}})();
