import {icon,iconButton,taskState,stateIcons} from './icons.js';
const CARD_LONG=260,CARD_FALLBACK=240,CARD_INFO_TOP=54,CARD_INFO_BOTTOM=76;
export class Board{
 constructor(el,{change,select,open,menu,action}){this.el=el;this.world=el.querySelector('.world');this.box=el.querySelector('.selection-box');this.items=[];this.view={x:40,y:40,z:1};this.selected=new Set();this.change=change;this.select=select;this.open=open;this.menu=menu;this.action=action;this.mode='select';this.space=false;this.history=[];this.redo=[];this.nodes=new Map();
 el.addEventListener('pointerdown',e=>this.down(e));el.addEventListener('pointermove',e=>this.move(e));el.addEventListener('pointerup',()=>this.end());el.addEventListener('pointercancel',()=>this.end());window.addEventListener('blur',()=>{this.space=false;this.end();});
 el.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY<0?1.12:1/1.12,e.clientX,e.clientY);},{passive:false});
 el.addEventListener('dblclick',e=>{const n=e.target.closest('.card');if(e.button===0&&n)this.open(n.dataset.id);});
 el.addEventListener('contextmenu',e=>{e.preventDefault();const n=e.target.closest('.card');if(n){if(!this.selected.has(n.dataset.id))this.selected=new Set([n.dataset.id]);this.paintSelection();this.menu(e,n.dataset.id);}});
 window.addEventListener('keydown',e=>{if(this.editable(e)||e.isComposing)return;if(e.code==='Space'){e.preventDefault();this.space=true;}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.remove();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();this.undo(e.shiftKey);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='a'){e.preventDefault();this.selected=new Set(this.items.map(i=>i.id));this.paintSelection();}if(e.key==='Escape'){this.selected.clear();this.paintSelection();}});
 window.addEventListener('keyup',e=>{if(e.code==='Space')this.space=false;});
 }
 editable(e){return !!document.querySelector('dialog[open]')||e.target.closest('input,textarea,select,button,[role=menu],[role=menuitem],[contenteditable=true]');}
 snapshot(){this.history.push(structuredClone(this.items));if(this.history.length>50)this.history.shift();this.redo=[];}
 undo(forward=false){const src=forward?this.redo:this.history,dest=forward?this.history:this.redo;if(!src.length)return;dest.push(structuredClone(this.items));this.items=src.pop();this.render();this.change();}
 remove(){if(!this.selected.size)return;this.snapshot();this.items=this.items.filter(i=>!this.selected.has(i.id));this.selected.clear();this.render();this.change();}
 point(x,y){const r=this.el.getBoundingClientRect();return{x:(x-r.left-this.view.x)/this.view.z,y:(y-r.top-this.view.y)/this.view.z};}
 transform(){this.world.style.transform=`translate(${this.view.x}px,${this.view.y}px) scale(${this.view.z})`;document.getElementById('zoom').textContent=Math.round(this.view.z*100)+'%';}
 zoom(f,x,y){const r=this.el.getBoundingClientRect();x??=r.left+r.width/2;y??=r.top+r.height/2;const p=this.point(x,y),z=Math.max(.08,Math.min(5,this.view.z*f));this.view={x:x-r.left-p.x*z,y:y-r.top-p.y*z,z};this.transform();this.change();}
 dimensions(i,info=this.info?.(i)||{}){const sourceWidth=Number(info.width),sourceHeight=Number(info.height);if(!(sourceWidth>0&&sourceHeight>0))return{width:CARD_FALLBACK,height:CARD_FALLBACK};const scale=CARD_LONG/Math.max(sourceWidth,sourceHeight),round=value=>Math.round(value*100)/100;return{width:Math.max(1,round(sourceWidth*scale)),height:Math.max(1,round(sourceHeight*scale))};}
 fit(){if(!this.items.length){this.view={x:40,y:40,z:1};}else{const boxes=this.items.map(i=>{const size=this.dimensions(i);return{left:i.x,top:i.y-CARD_INFO_TOP,right:i.x+size.width,bottom:i.y+size.height+CARD_INFO_BOTTOM};}),minx=Math.min(...boxes.map(b=>b.left)),miny=Math.min(...boxes.map(b=>b.top)),maxx=Math.max(...boxes.map(b=>b.right)),maxy=Math.max(...boxes.map(b=>b.bottom)),r=this.el.getBoundingClientRect(),dock=document.getElementById('generation-panel'),dockRect=dock?.getBoundingClientRect(),docked=dock&&getComputedStyle(dock).position==='absolute'&&getComputedStyle(dock).display!=='none',visibleHeight=docked&&dockRect.top>r.top?Math.max(160,dockRect.top-r.top-24):r.height,width=Math.max(1,maxx-minx),height=Math.max(1,maxy-miny),z=Math.min(1.5,Math.max(.08,Math.min((r.width-80)/width,(visibleHeight-80)/height)));this.view={x:(r.width-width*z)/2-minx*z,y:(visibleHeight-height*z)/2-miny*z,z};}this.transform();this.change();}
 add(data){this.snapshot();const p=this.point(this.el.getBoundingClientRect().left+60,this.el.getBoundingClientRect().top+60);const i={id:data.id||crypto.randomUUID(),asset_id:data.asset_id||null,x:data.x??p.x,y:data.y??p.y,label:data.label||''};this.items.push(i);this.render();this.change();return i;}
 down(e){if(e.button!==0&&e.button!==1)return;e.preventDefault();this.el.focus();const n=e.target.closest('.card'),p=this.point(e.clientX,e.clientY);if(e.button===1||this.space||this.mode==='pan'){this.el.setPointerCapture(e.pointerId);this.gesture={kind:'pan',x:e.clientX,y:e.clientY,view:{...this.view}};return;}
 if(n){const id=n.dataset.id;if(e.shiftKey){if(this.selected.has(id))this.selected.delete(id);else this.selected.add(id);}else if(!this.selected.has(id))this.selected=new Set([id]);this.paintSelection();this.gesture={kind:'drag',start:p,sx:e.clientX,sy:e.clientY,items:this.items.filter(i=>this.selected.has(i.id)).map(i=>({...i})),moved:false};}
 else{this.el.setPointerCapture(e.pointerId);const previous=e.shiftKey?new Set(this.selected):new Set();this.selected=previous;this.paintSelection();this.gesture={kind:'box',start:p,sx:e.clientX,sy:e.clientY,previous:new Set(previous)};}}
 move(e){const g=this.gesture;if(!g)return;const p=this.point(e.clientX,e.clientY);if(g.kind==='pan'){this.view.x=g.view.x+e.clientX-g.x;this.view.y=g.view.y+e.clientY-g.y;this.transform();}
 if(g.kind==='drag'){if(!g.moved&&Math.hypot(e.clientX-g.sx,e.clientY-g.sy)<4)return;if(!g.moved){this.el.setPointerCapture(e.pointerId);this.snapshot();g.moved=true;}for(const old of g.items){const i=this.items.find(i=>i.id===old.id);if(i){i.x=old.x+p.x-g.start.x;i.y=old.y+p.y-g.start.y;this.position(i);}}}
 if(g.kind==='box'){const x=Math.min(p.x,g.start.x),y=Math.min(p.y,g.start.y),w=Math.abs(p.x-g.start.x),h=Math.abs(p.y-g.start.y);this.box.hidden=false;Object.assign(this.box.style,{left:x*this.view.z+this.view.x+'px',top:y*this.view.z+this.view.y+'px',width:w*this.view.z+'px',height:h*this.view.z+'px'});this.selected=new Set([...g.previous,...this.items.filter(i=>{const size=this.dimensions(i);return i.x<x+w&&i.x+size.width>x&&i.y<y+h&&i.y+size.height>y;}).map(i=>i.id)]);this.paintSelection();}}
 end(){if(!this.gesture)return;const g=this.gesture;this.gesture=null;this.box.hidden=true;if(g.kind==='drag'&&g.moved||g.kind==='pan'&&(g.view.x!==this.view.x||g.view.y!==this.view.y))this.change();}
 position(i){const n=this.nodes.get(i.id);if(n)n.style.transform=`translate(${i.x}px,${i.y}px)`;}
 render(){
 const ids=new Set(this.items.map(i=>i.id));for(const [id,n]of this.nodes)if(!ids.has(id)){n.remove();this.nodes.delete(id);this.selected.delete(id);}
 for(const i of this.items){const info=this.info?.(i)||{},size=this.dimensions(i,info);let n=this.nodes.get(i.id);if(!n){
  n=document.createElement('article');n.className='card';n.dataset.id=i.id;n.tabIndex=0;
  const pic=document.createElement('div');pic.className='card-image';const caption=document.createElement('div');caption.className='card-caption';caption.append(document.createElement('p'),document.createElement('small'));
  const tools=document.createElement('div');tools.className='card-tools';tools.setAttribute('role','toolbar');tools.setAttribute('aria-label','图片操作');
  for(const [name,label,kind] of [['download','下载原图','download'],['cloud-upload','上传到 Drive','drive'],['more','更多操作','more']]){const b=iconButton(name,label,e=>{this.selected=new Set([i.id]);this.paintSelection();if(kind==='more'){const r=b.getBoundingClientRect();this.menu({clientX:r.left,clientY:r.bottom},i.id);}else this.action?.(kind);});b.addEventListener('pointerdown',e=>e.stopPropagation());b.addEventListener('dblclick',e=>e.stopPropagation());tools.append(b);}
  n.append(pic,caption,tools);n.addEventListener('keydown',e=>{if(e.target!==n)return;if(e.key==='Enter'){e.preventDefault();e.stopPropagation();this.open(i.id);}if(e.key===' '){e.preventDefault();e.stopPropagation();this.selected=new Set([i.id]);this.paintSelection();}});this.world.append(n);this.nodes.set(i.id,n);
 }
 n.style.width=size.width+'px';n.style.height=size.height+'px';n.dataset.cardWidth=String(size.width);n.dataset.cardHeight=String(size.height);const pic=n.firstChild,state=info.uploadState||taskState(i.label,!!i.asset_id);n.dataset.state=state;n.setAttribute('aria-label',(info.title||i.label||'图片')+'，双击或按 Enter 查看原图');
 if(info.url){let img=pic.querySelector('img');if(!img){pic.replaceChildren();img=document.createElement('img');img.draggable=false;img.loading='lazy';img.alt=info.title||'画布图片';img.addEventListener('error',()=>{n.dataset.state='failed';});pic.append(img);}if(img.getAttribute('src')!==info.url)img.src=info.url;}
 else if(pic.dataset.label!==i.label||pic.dataset.state!==state){pic.replaceChildren(icon(stateIcons[state],state==='generating'?'icon-lg spin':'icon-lg'));const status=document.createElement('span');status.textContent=i.label||'暂无缩略图';pic.append(status);if(state==='generating'){const progress=document.createElement('div');progress.className='card-progress';pic.append(progress);}pic.dataset.label=i.label;pic.dataset.state=state;}
 n.children[1].children[0].textContent=info.title||i.label||'图片';n.children[1].children[1].textContent=info.state||'';n.children[2].hidden=!i.asset_id;const upload=n.children[2].children[1];upload.disabled=state==='uploading';upload.title=state==='uploading'?'正在上传并校验':state==='uploaded'?'已上传到 Drive':state==='error'?'上传失败，可重试':'上传到 Drive';if(upload.dataset.state!==state){upload.replaceChildren(icon(state==='uploading'?'loading':state==='uploaded'?'uploaded':state==='error'?'error':'cloud-upload',state==='uploading'?'spin':''));upload.dataset.state=state;}this.position(i);
 }
 this.transform();this.paintSelection();document.getElementById('empty-board').hidden=!!this.items.length;
 }
 paintSelection(){for(const [id,n]of this.nodes)n.classList.toggle('selected',this.selected.has(id));this.select([...this.selected]);}
}
