export class Editor{
 constructor(dialog,save){this.d=dialog;this.c=dialog.querySelector('canvas');this.ctx=this.c.getContext('2d');this.save=save;this.ops=[];this.redo=[];this.tool='view';this.pending=null;this.fit=true;
 dialog.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{this.tool=b.dataset.tool;this.pending=null;dialog.querySelectorAll('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));this.c.style.cursor=this.tool==='view'?'zoom-in':'crosshair';this.render();});
 dialog.querySelector('#edit-close').onclick=()=>this.close();dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});
 dialog.querySelector('#edit-undo').onclick=()=>this.undo();dialog.querySelector('#edit-redo').onclick=()=>this.undo(true);
 dialog.querySelector('#edit-crop').onclick=()=>this.applyCrop();dialog.querySelector('#edit-text-apply').onclick=()=>this.applyText();
 dialog.querySelector('#edit-save').onclick=async()=>{if(this.pending)throwHint('请先确认裁切或文字，再保存');else{const b=dialog.querySelector('#edit-save');b.disabled=true;try{this.render();const blob=await new Promise(r=>this.c.toBlob(r,'image/png'));await this.save(blob,this.source,{operations:this.ops,source_width:this.bitmap.width,source_height:this.bitmap.height});this.close(true);}catch(e){throwHint(e.message);}finally{b.disabled=false;}}};
 this.c.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();if(this.tool==='view'){this.fit=!this.fit;this.sizing();return;}const p=this.point(e);if(this.tool==='text'){this.pending={type:'text',...this.style(),x:p.x,y:p.y};dialog.querySelector('#edit-text').hidden=false;dialog.querySelector('#edit-text-value').focus();return;}this.c.setPointerCapture(e.pointerId);this.drawing={type:this.tool,...this.style(),x:p.x,y:p.y,x2:p.x,y2:p.y,points:[p]};});
 this.c.addEventListener('pointermove',e=>{if(!this.drawing)return;const p=this.point(e);this.drawing.x2=p.x;this.drawing.y2=p.y;if(this.tool==='pen'){const last=this.drawing.points.at(-1);if(Math.hypot(last.x-p.x,last.y-p.y)>Math.max(1,this.drawing.width/4)&&this.drawing.points.length<2000)this.drawing.points.push({x:Math.round(p.x*10)/10,y:Math.round(p.y*10)/10});}this.render();this.draw(this.drawing,true);});
 this.c.addEventListener('pointerup',()=>{if(!this.drawing)return;const op=this.drawing;this.drawing=null;if(op.type==='crop'){this.pending=op;this.render();}else{if(this.ops.length>=150){this.d.querySelector('#edit-notice').textContent='本次编辑已达到 150 步，请另存副本后继续';this.render();return;}this.ops.push(op);this.redo=[];this.render();}});
 this.c.addEventListener('pointercancel',()=>{this.drawing=null;this.render();});
 dialog.addEventListener('keydown',e=>{e.stopPropagation();if(e.isComposing||e.target.closest('[data-color-picker]'))return;const text=e.target.matches('input,textarea');if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();this.applyText();return;}if(text)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();this.undo(e.shiftKey);}if(e.key==='Enter'){e.preventDefault();this.applyCrop();}if(e.key==='Escape'&&this.pending){e.preventDefault();this.pending=null;this.render();}});
 function throwHint(t){dialog.querySelector('#edit-notice').textContent=t;}
 }
 style(){return{color:this.d.querySelector('#edit-color').value,width:Math.max(1,Math.min(100,Number(this.d.querySelector('#edit-width').value)||6)),font:Math.max(8,Math.min(300,Number(this.d.querySelector('#edit-font').value)||48))};}
 point(e){const r=this.c.getBoundingClientRect();return{x:Math.max(0,Math.min(this.c.width,(e.clientX-r.left)*this.c.width/r.width)),y:Math.max(0,Math.min(this.c.height,(e.clientY-r.top)*this.c.height/r.height))};}
 async open(blob,source){this.bitmap?.close();this.bitmap=await createImageBitmap(blob);this.source=source;this.ops=[];this.redo=[];this.pending=null;this.fit=true;this.tool='view';this.d.querySelector('#edit-notice').textContent='双击画布打开原图；此处点击图片切换适应 / 100%。编辑另存为副本。';this.d.querySelector('#edit-text').hidden=true;this.d.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool==='view'));this.d.showModal();this.render();}
 close(force=false){if(!force&&this.ops.length&&!confirm('放弃这次尚未保存的编辑？'))return;this.d.close();this.bitmap?.close();this.bitmap=null;this.c.width=1;this.c.height=1;}
 sizing(){this.c.style.maxWidth=this.fit?'100%':'none';this.c.style.maxHeight=this.fit?'100%':'none';this.c.style.width=this.fit?'auto':this.c.width+'px';this.c.style.height=this.fit?'auto':this.c.height+'px';this.d.querySelector('#edit-dimensions').textContent=`${this.c.width} × ${this.c.height} · ${this.fit?'适应窗口':'100%'}`;}
 render(){if(!this.bitmap)return;this.c.width=this.bitmap.width;this.c.height=this.bitmap.height;this.ctx.drawImage(this.bitmap,0,0);for(const op of this.ops){if(op.type==='crop'){const temp=document.createElement('canvas');temp.width=op.w;temp.height=op.h;temp.getContext('2d').drawImage(this.c,op.x,op.y,op.w,op.h,0,0,op.w,op.h);this.c.width=op.w;this.c.height=op.h;this.ctx.drawImage(temp,0,0);}else this.draw(op);}if(this.pending?.type==='crop')this.draw(this.pending,true);this.sizing();this.d.querySelector('#edit-crop').hidden=this.pending?.type!=='crop';this.d.querySelector('#edit-undo').disabled=!this.ops.length;this.d.querySelector('#edit-redo').disabled=!this.redo.length;}
 draw(op,preview=false){const c=this.ctx;c.save();c.strokeStyle=op.color;c.fillStyle=op.color;c.lineWidth=op.width;c.lineCap='round';c.lineJoin='round';c.beginPath();if(op.type==='pen'){op.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));if(op.points.length===1){c.arc(op.x,op.y,op.width/2,0,Math.PI*2);c.fill();}else c.stroke();}if(op.type==='rectangle'||op.type==='crop'){if(op.type==='crop'){c.strokeStyle='#78dcbe';c.lineWidth=Math.max(2,this.c.width/400);c.setLineDash([c.lineWidth*3,c.lineWidth*2]);}c.strokeRect(op.x,op.y,op.x2-op.x,op.y2-op.y);}if(op.type==='arrow'){c.moveTo(op.x,op.y);c.lineTo(op.x2,op.y2);c.stroke();const angle=Math.atan2(op.y2-op.y,op.x2-op.x),s=Math.max(15,op.width*4);c.beginPath();c.moveTo(op.x2,op.y2);c.lineTo(op.x2-s*Math.cos(angle-.45),op.y2-s*Math.sin(angle-.45));c.lineTo(op.x2-s*Math.cos(angle+.45),op.y2-s*Math.sin(angle+.45));c.closePath();c.fill();}if(op.type==='text'&&op.text){c.font=`${op.font}px sans-serif`;c.textBaseline='top';op.text.split('\n').forEach((t,i)=>c.fillText(t,op.x,op.y+i*op.font*1.25));}c.restore();}
 applyCrop(){const p=this.pending;if(p?.type!=='crop')return;const x=Math.floor(Math.min(p.x,p.x2)),y=Math.floor(Math.min(p.y,p.y2)),w=Math.floor(Math.abs(p.x2-p.x)),h=Math.floor(Math.abs(p.y2-p.y));if(w<2||h<2)return;this.ops.push({type:'crop',x,y,w,h});this.pending=null;this.redo=[];this.render();}
 applyText(){if(this.pending?.type!=='text')return;const text=this.d.querySelector('#edit-text-value').value;if(text)this.ops.push({...this.pending,text});this.pending=null;this.redo=[];this.d.querySelector('#edit-text-value').value='';this.d.querySelector('#edit-text').hidden=true;this.render();}
 undo(forward=false){this.pending=null;const src=forward?this.redo:this.ops,dest=forward?this.ops:this.redo;if(src.length)dest.push(src.pop());this.render();}
}
