let dbPromise;const memory=new Map();
function db(){return dbPromise??=new Promise((resolve,reject)=>{const r=indexedDB.open('ctmoai-originals-v3',1);r.onupgradeneeded=()=>{r.result.createObjectStore('originals');r.result.createObjectStore('settings');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('浏览器恢复缓存不可用'));});}
export async function local(store,key,value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(store,value===undefined?'readonly':'readwrite'),r=value===undefined?tx.objectStore(store).get(key):tx.objectStore(store).put(value,key);let result;r.onsuccess=()=>{result=r.result;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(new Error('浏览器缓存保存失败，请立即下载原图'));tx.onabort=tx.onerror;});}
export async function keep(id,blob){memory.set(id,blob);await local('originals',id,blob);}
export async function cached(id){return memory.get(id)||await local('originals',id).catch(()=>null);}
export async function hash(blob){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export const dataURL=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('文件读取失败'));r.readAsDataURL(blob);});
export function decode(pic){return new Blob([Uint8Array.from(atob(pic.data),c=>c.charCodeAt(0))],{type:pic.mime});}
export async function thumbnail(blob){const img=await createImageBitmap(blob),c=document.createElement('canvas'),scale=Math.min(1,512/Math.max(img.width,img.height));c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);img.close();let b=await new Promise(r=>c.toBlob(r,'image/webp',.72));if(b.size>131072)b=await new Promise(r=>c.toBlob(r,'image/webp',.35));if(b.size>131072)throw new Error('缩略图超过上限，原图仍可下载');return b;}
export function filename(a){return 'ctmoai-'+a.id+'.'+({'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[a.mime]||'png');}
export function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
let directory=null;
export async function chooseDirectory(){if(!window.showDirectoryPicker)throw new Error('此浏览器不支持直接写文件夹，请使用下载原图');directory=await window.showDirectoryPicker({mode:'readwrite'});await local('settings','directory',directory).catch(()=>{});return directory.name;}
export async function restoreDirectory(){directory=await local('settings','directory').catch(()=>null);if(directory&&await directory.queryPermission({mode:'readwrite'})==='granted')return directory.name;directory=null;return null;}
export async function saveFile(a,blob){if(!directory)return false;if(await directory.queryPermission({mode:'readwrite'})!=='granted'){directory=null;throw new Error('文件夹权限已失效，请重新选择文件夹或下载');}const h=await directory.getFileHandle(filename(a),{create:true}),w=await h.createWritable();try{await w.write(blob);await w.close();const actual=await h.getFile();if(actual.size!==blob.size||await hash(actual)!==await hash(blob))throw new Error('本地文件校验失败');await local('settings','saved:'+a.id,{name:filename(a),at:Date.now()}).catch(()=>{});return true;}catch(e){await w.abort().catch(()=>{});throw e;}}
