import {icon} from './icons.js';
export class Viewer{
 constructor(dialog,original){this.dialog=dialog;this.original=original;this.image=dialog.querySelector('img');this.stage=dialog.querySelector('.viewer-stage');this.version=0;this.url=null;this.zoom=1;
 dialog.querySelector('#viewer-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{this.version++;if(this.url)URL.revokeObjectURL(this.url);this.url=null;this.image.removeAttribute('src');});
 dialog.querySelector('#viewer-fit').onclick=()=>this.fit();dialog.querySelector('#viewer-actual').onclick=()=>this.scale(1);
 this.stage.addEventListener('wheel',e=>{e.preventDefault();this.scale(this.zoom*(e.deltaY<0?1.15:1/1.15));},{passive:false});
 this.stage.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();this.stage.setPointerCapture(e.pointerId);this.drag={x:e.clientX,y:e.clientY,left:this.stage.scrollLeft,top:this.stage.scrollTop};});this.stage.addEventListener('pointermove',e=>{if(this.drag){this.stage.scrollLeft=this.drag.left+this.drag.x-e.clientX;this.stage.scrollTop=this.drag.top+this.drag.y-e.clientY;}});for(const name of ['pointerup','pointercancel'])this.stage.addEventListener(name,()=>{this.drag=null;});
 }
 feedback(state,message=''){this.stage.dataset.state=state;this.stage.setAttribute('aria-busy',String(state==='loading'));const box=this.stage.querySelector('.viewer-feedback');box.hidden=state==='ready';box.querySelector('.viewer-feedback-icon').replaceChildren(icon(state==='loading'?'loading':'error',state==='loading'?'icon-lg spin':'icon-lg'));box.querySelector('h2').textContent=state==='loading'?'正在载入原图':'无法读取原图';box.querySelector('p').textContent=message||'稍候即可查看完整尺寸';}
 scale(z){this.zoom=Math.max(.02,Math.min(4,z));this.image.style.width=Math.round(this.width*this.zoom)+'px';this.image.style.height=Math.round(this.height*this.zoom)+'px';this.dialog.querySelector('#viewer-info').textContent=`${this.width} × ${this.height} · ${Math.round(this.zoom*100)}%`;}
 fit(){this.scale(Math.min(1,(this.stage.clientWidth-30)/this.width,(this.stage.clientHeight-30)/this.height));}
 async open(asset){const version=++this.version;this.width=asset.width;this.height=asset.height;this.dialog.querySelector('#viewer-info').textContent='正在读取原图…';this.image.removeAttribute('src');this.feedback('loading');if(!this.dialog.open)this.dialog.showModal();try{const blob=await this.original(asset);if(version!==this.version)return;if(this.url)URL.revokeObjectURL(this.url);this.url=URL.createObjectURL(blob);this.image.src=this.url;await this.image.decode();if(version===this.version){this.fit();this.feedback('ready');}}catch(e){if(version===this.version){this.dialog.querySelector('#viewer-info').textContent=e.message;this.feedback('error',e.message);}}}
}
